### ISSUE TITLE

Please

### ISSUE THREAD

**Issue by AntonProkudin** [NikolayV11/sportova#1]
Please upload the MySQL scripts

**Comment by NikolayV11** [comment]
не понял что хочешь?
что за скрипты? 
в смысле саму таблицу из MySQL?!

**Comment by AntonProkudin** [comment]
Скрипт создания таблицы

пн, 4 мар. 2024 г., 10:06 Николай ***@***.***>:

**Comment by NikolayV11** [comment]
я таблицы еще не доделал и в beckend не знаю, у меня установлен OpenServer и там я делаю таблицы через phpMyAdmin,
тебе нужна эта таблица ?

**Comment by AntonProkudin** [comment]
Да, в open server можно сделать дамп бд

пн, 4 мар. 2024 г., 12:19 Николай ***@***.***>:

**Comment by NikolayV11** [comment]
смотри новый коммит 04 2024 14:30:52 
информации там очень мало

**Comment by AntonProkudin** [comment]
Спасибо

пн, 4 мар. 2024 г., 12:34 Николай ***@***.***>:
